### PR TITLE
pandoc v1.17.0.1

### PR DESCRIPTION
**Pull request by janschulz**
Includes 
https://github.com/jgm/pandoc/releases/tag/1.17
https://github.com/jgm/pandoc/releases/tag/1.17.0.1

### CODE REVIEW

**Comment by ocefpaf** [comment]
What happened to AppVeyor?

**Comment by janschulz** [comment]
I finally canceled it as the other two platforms were a success (and the only thing done here is a unzip :-))

**Comment by ocefpaf** [comment]
Makes sense. Keep an eye on the status though. Something a broken file or bad checksum might bite us later.

**Comment by janschulz** [comment]
and all is good :-) -> build passed

**Pull request merged**
