### PR TITLE
Revert "repack pandoc 2.2.1 RPM from Fedora on ppc64le"

### PR DESCRIPTION
**Pull request by ickc**
This reverts commit 422f9b56da8a0c337df04e391f3fd51e65e2f582.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

c.f. #71, #72

### CODE REVIEW

**Comment by ickc** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
Why are you reverting that? Can you give is more context and, better yet, ping the team for a review?

**Comment by ickc** [comment]
It is explained in #72. It is not working and until it is working it should not be in master.

Are you done with your drama?

**Comment by ocefpaf** [comment]
> Are you done with your drama?

You edit your message afterwards and respect to the maintainers team is not drama. Please act with the maintainers team and not against them.

**Comment by ickc** [comment]
I edit it Before you were even asking. I was already chasing the history in #71, #72 in doing the revert. And again what makes you think a core member should merge something not working and not reverting it? Or are you bullying non-core members?

**Comment by ickc** [comment]
@ocefpaf, I caught you red-handed:

At Jan 27, 2022, 12:05 PM PST as shown in the edit history, I edited this PR to include the reference to PR #71, #72.

At [Jan 27, 2022, 12:08 PM PST](https://github.com/conda-forge/pandoc-feedstock/pull/72#issuecomment-1023596597), in the link I explained why #72 is closing, including pointing out #71 isn't working.

At [Jan 27, 2022, 12:56 PM PST](https://github.com/conda-forge/pandoc-feedstock/pull/108#issuecomment-1023631564), you asked

> Why are you reverting that? Can you give is more context and, better yet, ping the team for a review?

And [later](https://github.com/conda-forge/pandoc-feedstock/pull/108#issuecomment-1024036722) you accused me of

> You edit your message afterwards and respect to the maintainers team is not drama. Please act with the maintainers team and not against them.

This proves that you are making up things to accuse me because you, as a core member, do not like people pointing out to you that you close an issue prematurely without explanations.

@beckermr, can you lock this as well? Thanks.

**Comment by ocefpaf** [comment]
You know how notifications work @ickc. When I received it your edits were not there. Also, that is not relevant as my questions was just for clarifications. Please reconsider your aggressive behavior, this is not acceptable.

**Comment by ickc** [comment]
You know how notifications work @ocefpaf. When you make an accusation like that, you better check your facts first.

Please reconsider your aggressive behavior. Just because you have been maintaining this for a long time does not make you right automatically. Please stop being trigger happy, closing things or accusing someone self-merging controversial stuffs (where again if you follow the references you should know it is completely normal maintenance stuffs.)

You just added yet another instance of aggressive behavior—after someone locked the conversation, you abuse your status being a collaborators here and continue to discuss, with no apology to the wrongful accusation and misdirecting by pointing that back to me. This is not acceptable and your action has been recorded for the world to see.

**Comment by beckermr** [comment]
Comments on a locked thread were posted here, whether on purpose or by accident due to timing. From now on, please refrain from doing so even if you have access. You can reach out to me on Gitter (beckermr) if you have questions or concerns. 

Aggressive behavior on conda-forge is not acceptable and will result in us having to take action should it continue.

**Pull request merged**
