### PR TITLE
Add ppc64le

### LINKED ISSUE #68: Build for ppc64le?
Only a single version, 2.0.0.1, was published for ppc64le. Its dependency `libffi` 3.2 now conflicts with recent versions of Python that use `libffi` 3.3. I've opened ContinuumIO/anaconda-issues/issues/11887 about that.

What options are there to get a newer package with updated dependencies for ppc64le?
- Building from source as suggested in #54.
- Repackaging [an RPM](http://rpmfind.net/linux/rpm2html/search.php?query=pandoc&submit=Search+...&system=&arch=ppc64le), as it was done for 2.0.0.1.
- ???

Building from source would have the advantage of providing the same package version across different platforms.

As for RPMs, would it even be possible to release for ppc64le at a different version than the other platforms? The currently supported platforms should continue to repackage the official builds for the latest version.

### PR DESCRIPTION
**Pull request by jjhelmus**
Enable a build for ppc64le be repackaging a RPM from EPEL

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #68

### CODE REVIEW

**Comment by jjhelmus** [comment]
Specifically the RPM come from https://copr.fedorainfracloud.org/coprs/petersen/pandoc/.  I was not able to find a similar package for aarch64.

**Comment by jjhelmus** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
LGTM, thanks!

**Comment by rolweber** [comment]
Thank you!

**Pull request merged**
