### PR TITLE
Build from source

### LINKED ISSUE #54: Build from source?
We have the haskell build tools.  this should be feasible

### PR DESCRIPTION
**Pull request by m-rossi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This an attempt to close #54 using `stack` as I joined the Mac M1 club and was looking for binaries of Pandoc for my new laptop. My local tests had some success, so let's see how far I can bring this PR.

### CODE REVIEW

**Comment by m-rossi** [comment]
@conda-forge-admin, please rerender

**Comment by m-rossi** [comment]
@conda-forge-admin, please rerender

**Comment by m-rossi** [comment]
@conda-forge-admin, please rerender

**Comment by m-rossi** [comment]
@conda-forge-admin, please rerender

**Comment by m-rossi** [comment]
@conda-forge-admin, please rerender

**Comment by m-rossi** [comment]
@conda-forge/pandoc this is ready for review.

**Comment by ocefpaf** [comment]
> @conda-forge/pandoc this is ready for review.

@m-rossi impressive! I'm definitely not the right person to review this b/c I'm not familiar with haskell. @msarahan do you have some spare cycles to look into this?

**Comment by m-rossi** [comment]
@conda-forge/pandoc Any update?

**Comment by msarahan** [comment]
Seems fine to me. I apologize for the delay. I missed this. The hardest part for me was always getting the precursors built (stack or ghcup), but I was stuck on aarch64 especially. This PR doesn't address that, but the repackage approach there is fine. It's better to have this building from source where we can, rather than not at all.

Nice work @m-rossi

**Pull request merged**
