### PR TITLE
gmp and zlib deps are obsolete

### PR DESCRIPTION
**Pull request by kiwi0fruit**
See https://github.com/jgm/pandoc/issues/5281

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kiwi0fruit** [comment]
@jankatins @dhimmel What do you think about gmp and zlib deps on lInux? Are they obsolete?

**Comment by kiwi0fruit** [comment]
@conda-forge-admin, please rerender

**Comment by kiwi0fruit** [comment]
@conda-forge-admin, please rerender

**Comment by kiwi0fruit** [comment]
@jankatins @ocefpaf @dhimmel please merge PR.

As it's already a second my contribution to this recipe I added myself to the recipe maintainers.

**Comment by ocefpaf** [comment]
Let's wait for @mariusvniekerk's #51 then we can rebase this one and merge. Thanks @kiwi0fruit!

**Comment by mariusvniekerk** [comment]
We can land this earlier

**Pull request merged**
