### PR TITLE
update to 2.4

### PR DESCRIPTION
**Pull request by ocefpaf**
@CJ-Wright the bot is missing this one :-/

### CODE REVIEW

**Comment by CJ-Wright** [comment]
The bot's been down for about 20 hours.

**Comment by ocefpaf** [comment]
OS X is failing with:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool:
object: /Users/travis/miniconda3/conda-bld/pandoc_1541518526180/_h_env/bin/pandoc-citeproc malformed object (unknown load command 9)
```

**Comment by ocefpaf** [comment]
> The bot's been down for about 20 hours.

It did not catch the last two updates too and this release was issued 2 days ago.

**Comment by CJ-Wright** [comment]
Hmm ok

**Comment by ocefpaf** [comment]
@msarahan even when I use the `fn` (tested locally) conda-build insists on being smarter than me and creates the structure below:

```shell
ls -lha /opt/conda/conda-bld/pandoc_1543073081704/work
conda_build.sh	control.tar.gz	data.tar.xz  debian-binary
```

I can adapt our build scripts to use that but it is not really intuitive.
Am I doing something wrong? Is there a way to work around it?

**Comment by CJ-Wright** [comment]
@ocefpaf the graph has this recipe as 'bad' filed under `'make_graph: missing url'`. So maybe the render isn't working properly or something is getting lost?

**Pull request merged**
