### PR TITLE
update to 2.1.1

### PR DESCRIPTION
**Pull request by ocefpaf**
See https://github.com/jgm/pandoc/releases/tag/2.1.1

### CODE REVIEW

**Comment by ocefpaf** [comment]
Looks like @janschulz is @jankatins now. @jankatins can you confirm this? Should I add you again to pandoc under @jankatins ?

**Comment by dhimmel** [comment]
Nice. This will fix the extra brackets for citations in captions issue https://github.com/jgm/pandoc/issues/4272.

@ocefpaf IIRC, there was a one-line command you can run to automatically make these version upgrade changes to the recipe? Is that the case and what is it?

**Comment by ocefpaf** [comment]
> @ocefpaf IIRC, there was a one-line command you can run to automatically make these version upgrade changes to the recipe?

For pandoc's case no b/c we are repackaging and the binaries, so the changes here are not specific enough to play nice with conda-forge's scripts to update recipes.

> Is that the case and what is it?

I download the binaries, [compute the checksum](https://github.com/conda-forge/staged-recipes#2-how-do-i-populate-the-hash-field), update the version, and send the PR.

**Comment by jankatins** [comment]
Yep:  @janschulz -> @jankatins is correct. Damn, I forgot that these handles are part of the feedstock repos :-(

**Comment by ocefpaf** [comment]
> Removing me ist fine this case, you are handling it better than I ever could!

I interpreted the ist as a is not at first but now that I read it seems you are OK being out. Anyway, if you don't mind, I'd rather to still have you on the team :wink: 

PS: there are a few feedstocks with `janschulz`. See https://github.com/search?q=org%3Aconda-forge+janschulz&type=Code

**Comment by jankatins** [comment]
Sorry, 'ist' = 'is' (German autocorrect...). I will send PRs for all the other Repos

**Comment by ocefpaf** [comment]
Travis-CI passed on [my instance](https://travis-ci.org/ocefpaf/pandoc-feedstock/), merging this.

**Pull request merged**
