### PR TITLE
bump to v3.1.8

### PR DESCRIPTION
**Pull request by mfansler**
Bumping version; adding myself as maintainer.

## Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by mfansler** [comment]
Looks like [upstream switched to `cabal` instead of `stack`](https://github.com/jgm/pandoc/compare/3.1.3...3.1.8#diff-0ee926c5a249e740fa8422c1d356af17c9ab3f98e150ec8bdf2490aa17320aa7) since our last successful build.

**Comment by m-rossi** [comment]
> Looks like [upstream switched to `cabal` instead of `stack`](https://github.com/jgm/pandoc/compare/3.1.3...3.1.8#diff-0ee926c5a249e740fa8422c1d356af17c9ab3f98e150ec8bdf2490aa17320aa7) since our last successful build.

I also made several attempts to make the builds work again (with no luck) using stack. Therefore I thought we should  move the feedstock back to binary repackaging?

**Comment by ocefpaf** [comment]
> Therefore I thought we should move the feedstock back to binary repackaging?

I'm ok with it. Pandoc is not easy to build and we are limited on time to keep it in sync with upstream.

**Comment by m-rossi** [comment]
Closing in favor of #139

**Pull request closed without merging**
