### PR TITLE
v2.5

### PR DESCRIPTION
**Pull request by ocefpaf**
@CJ-Wright these updates are still not getting picked up by the bot. Is there something we need to do to "fix" the recipe?

### CODE REVIEW

**Comment by CJ-Wright** [comment]
see: https://github.com/conda-forge/pandoc-feedstock/pull/45#issuecomment-441410584

**Comment by ocefpaf** [comment]
> see: [#45 (comment)](https://github.com/conda-forge/pandoc-feedstock/pull/45#issuecomment-441410584)

That is:

> @ocefpaf the graph has this recipe as 'bad' filed under 'make_graph: missing url'. So maybe the render isn't working properly or something is getting lost?

Not sure about that b/c the recipe is re-rendering just fine and the URL is being picked up. It may be something else.

**Comment by CJ-Wright** [comment]
Sorry I meant the render in the conda-build render (so the making of the yaml file).

**Comment by ocefpaf** [comment]
> Sorry I meant the render in the conda-build render (so the making of the yaml file).

I could not find how to render with `conda-build` but `conda-render` seems to wor on Linux:

```shell
> conda render recipe   
--------------
Hash contents:
--------------
{}
----------
meta.yaml:
----------
package:
    name: pandoc
    version: '2.5'
source:
    fn: pandoc.deb
    sha256: 56c6bd9613818c71594052d676d898dbb88580b266ec98f1becf9a97bac7aa37
    url: https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-1-amd64.deb
build:
    number: '0'
requirements:
    run:
        - zlib
        - gmp
test:
    commands:
        - pandoc --help
        - pandoc --version
about:
    home: http://pandoc.org/
    license: GPL-2.0
    summary: Universal markup converter (repackaged binaries)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jankatins
        - ocefpaf
        - dhimmel
```

**Pull request merged**
